import = [
    "~/.config/alacritty/themes/themes/ayu_dark.toml"
]

[env]
TERM = "xterm-256color"

[shell]
program = "/opt/homebrew/bin/tmux"

[window]
padding.x = 10
padding.y = 10

decorations = "Buttonless"

opacity = 1.0
blur = true

option_as_alt = "Both"

[font]
normal.family = "JetBrainsMono Nerd Font Mono"
normal.style = "Thin"
bold.family = "JetBrainsMono Nerd Font Mono"
bold.style = "Regular"
# normal.family = "MesloLGL Nerd Font Propo"
size = 14

[selection]
save_to_clipboard = true
